packages:
  - apps/**
  - examples/**
  - packages/**

catalog:
  '@fontsource-variable/open-sans': ^5.2.6
  '@fontsource-variable/public-sans': ^5.2.6
  '@fontsource-variable/roboto-mono': ^5.2.6
  '@fontsource-variable/source-sans-3': ^5.2.8
  '@fontsource/merriweather': ^5.2.9
  '@iconify/json': ^2.2.359
  '@iconify/tailwind4': ^1.0.6
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@zag-js/anatomy': ^1.18.3
  '@zag-js/aria-hidden': ^1.18.3
  '@zag-js/core': ^1.18.3
  '@zag-js/dismissable': ^1.18.3
  '@zag-js/dom-query': ^1.18.3
  '@zag-js/focus-trap': ^1.18.3
  '@zag-js/remove-scroll': ^1.18.3
  '@zag-js/types': ^1.18.3
  '@zag-js/utils': ^1.18.3
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vite: ^7.0.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
