name: pkg.pr.new (compat)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build with Turbo
        run: pnpm turbo run build

      - name: Upload package
        run: pnpm dlx pkg-pr-new './packages/compat'
